FROM ubuntu:18.04

ENV PROVISIONING_HOME=/root/provisioning
ENV PROVISIONED_DATA=/root/data
ENV TILEMILL_HOME=/opt/tilemill
ENV GDAL_SCRIPTS_HOME=/opt/gdal-postmates
ENV MB_UTIL_HOME=/opt/mbutil

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update -y \
 && apt-get install -y --no-install-recommends apt-utils \
 && apt-get install -y locales && locale-gen en_US.UTF-8 \
 && apt-get install -y curl \
 && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
 && apt-get update -y \
 && apt-get install -y nodejs git gdal-bin python3-gdal wget unzip python3-pip

RUN mkdir -p ${TILEMILL_HOME}
RUN git clone https://github.com/tilemill-project/tilemill.git ${TILEMILL_HOME}
RUN cd ${TILEMILL_HOME}
RUN npm --prefix ${TILEMILL_HOME} install ${TILEMILL_HOME}
RUN mkdir -p ${GDAL_SCRIPTS_HOME}
RUN git clone https://github.com/postmates/gdal.git ${GDAL_SCRIPTS_HOME}
RUN mkdir -p ${MB_UTIL_HOME}
RUN git clone https://github.com/mapbox/mbutil.git ${MB_UTIL_HOME}
RUN pip3 install pyproj
RUN mkdir -p ${PROVISIONING_HOME}
RUN git clone --depth=1 --branch=master git://github.com/tomfumb/BVSAR-map-data-provisioner ${PROVISIONING_HOME}
RUN rm -rf $PROVISIONING_HOME/.git*
RUN rm -rf /root/Documents/MapBox/project/*
RUN mkdir -p ${PROVISIONED_DATA}

EXPOSE 20008
EXPOSE 20009

VOLUME ${PROVISIONING_HOME}
VOLUME ${PROVISIONED_DATA}

WORKDIR ${PROVISIONING_HOME}

CMD $PROVISIONING_HOME/docker/run_tilemill.sh
